name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - uses: pre-commit/action@v3.0.1

  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO: [jazzy]
        ROS_REPO: [testing, main]
    env:
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          UPSTREAM_WORKSPACE: "github:RaphRover/raph_common#main"
          CMAKE_ARGS: "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
